services:
  nginx:
    image: nginx:1-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  backend:
    build:
      context: ./backend
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000