networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "22"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on: 
      - frontend
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - dev
